# Generated by Django 4.1.2 on 2022-10-20 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='compressing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_240',
            field=models.FileField(blank=True, null=True, upload_to='videos_240', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='videos_360', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
